### ISSUE TITLE
Disabled Elites cause beefy normal enemies to spawn

### ISSUE THREAD

**Issue by goldenguy00** [prodzpod/RisingTides#2]
This is an enemy that spawned almost immediately when using honor (also happens without honor, this is just an easy way to test)

![{63758F7B-95AA-4FA5-BBAE-FF431B2E6477}](https://github.com/user-attachments/assets/c233d263-bf93-4447-bc37-fc8b8a6fa7fe)

(this is boostDamage and boostHp respectively)
![{6A14D663-E604-4A4D-A7D2-F10597E9C274}](https://github.com/user-attachments/assets/4ee97ba7-d9e1-4aa9-ab5d-dd87f630d57d)

![{ADE69B84-6092-4580-A3B0-240459E8606B}](https://github.com/user-attachments/assets/6cfe83b9-eed0-4d29-bfc6-dfb87848d649)

![{C8A08BB7-F5AD-439F-BB37-CF94092FF99F}](https://github.com/user-attachments/assets/2b723476-c78f-48aa-b0c2-e29981a6ad01)

**Comment by prodzpod** [comment]
makes sense
